In [1]:
import numpy as np

In [ ]:
# Printing of Numpy Arrays

In [ ]:
# 1. 1D Arrays

In [5]:
a=np.arange(6)   # 1 Dimensional(1D) Array 

In [6]:
print(a)

[0 1 2 3 4 5]


In [7]:
type(a)

numpy.ndarray

In [ ]:
# 2. 2D Arrays

In [8]:
b=np.arange(12).reshape(4,3)  # 2D array  4*3 = 12

In [9]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
b=np.arange(12).reshape(5,2) # 5*2 = 10, which doesnt match to the arange 12. so errored.

ValueError: cannot reshape array of size 12 into shape (5,2)

In [ ]:
# 3. 3D arrays

In [12]:
c=np.arange(24).reshape(2,3,4) # 2*3*4 = 24

print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [14]:
d=np.arange(8).reshape(2,2,2) # 2*2*2 = 8

print(d)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# 4. Introduction to Stastical concepts  (Mean & Median)

In [19]:
test_scores=np.array([32.32,56.98,21.52,44.32,55.63,13.75,43.47,43.34]) # mean = sum of all elements/no.of elements

In [20]:
print('Mean test scores are calculated below: ')

print(np.mean(test_scores))

Mean test scores are calculated below: 
38.91625


In [21]:
print('Median test scores are calculated below:')

print(np.median(test_scores))

Median test scores are calculated below:
43.405
