In [ ]:
# UNDERSTANDING NUMPY

In [ ]:
# 1. To Install Numpy

In [3]:
!pip install numpy

In [7]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\devisivaneni\anaconda3\lib\site-packages (1.18.2)


In [8]:
import numpy as np # np is alias name to numpy

In [9]:
array_one = np.array([1,2,3,4,5,6])

array_one

array([1, 2, 3, 4, 5, 6])

In [12]:
type(array_one)

numpy.ndarray

In [13]:
values = [1,2,3,4,5,6,7,8,9,10]

array_two = np.array(values)

array_two

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# To create an array of zeros with desired shape(x,y)

In [15]:
array_zeros = np.zeros((3,4))

array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])