In [ ]:
#Basic Operations in Numpy

In [1]:
import numpy as np

In [ ]:
# 1. Addition of two arrays

In [4]:
a = np.array([10,10,20])
b = np.array([5,5,10])

In [5]:
a+b

array([15, 15, 30])

In [ ]:
# 2. Substraction of two arrays

In [6]:
a-b

array([ 5,  5, 10])

In [ ]:
# 3. Multiplication of two arrays

In [7]:
a*b

array([ 50,  50, 200])

In [ ]:
# 4. division of two arrays

In [8]:
a/b     #2.----> point or decimal

array([2., 2., 2.])

In [ ]:
#5. Modulus operator ---> which returns the remainder

In [9]:
a%b

array([0, 0, 0], dtype=int32)

In [10]:
a%4

array([2, 2, 0], dtype=int32)

In [11]:
b%2

array([1, 1, 0], dtype=int32)

In [ ]:
#6. Comparison operator

In [12]:
a<30      # 10<30, 10<30, 20<30

array([ True,  True,  True])

In [13]:
b>20     #5>20, 5>20, 10>20

array([False, False, False])

In [ ]:
#7. Exponential Operator

In [14]:
a**2

array([100, 100, 400], dtype=int32)

In [15]:
b**3

array([ 125,  125, 1000], dtype=int32)

In [ ]:
#8. To modify the existing array

In [22]:
a +=5

a

array([15, 15, 25])

In [23]:
b +=a

b

array([20, 20, 35])

In [24]:
a

array([15, 15, 25])

In [25]:
b

array([20, 20, 35])

In [ ]:
#9. Unary Operator

In [27]:
ages = np.array([10,15,20,30,40])

ages

array([10, 15, 20, 30, 40])

In [28]:
ages.sum()

115

In [29]:
ages.max()

40

In [30]:
ages.min()

10

In [ ]:
#10. reshape method

In [31]:
number = np.arange(12).reshape(3,4)

number

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])